export interface SalaryReport {
    thang: string,
    employee_id: string,
    ngay_cong_chuan: number,
    ngay_cong_tinh_luong: number,
    ngay_cong_OT: number,
    cong_tac_phi: number,
    thuong: number,
    phut_di_muon: number,
    luong_theo_ngay_cong: number,
    luong_OT: number,
    phu_cap_an_trua: number,
    phu_cap_khac: number,
    tru_di_muon: number,
    khoan_tru_khac: number,
    tong_thu_nhap: number,
    luong_OT_duoc_mien_thue: number,
    tien_an_duoc_mien_thue: number,
    bao_hiem: number,
    giam_tru_gia_canh: number,
    thu_nhap_tinh_thue: number,
    thue_TNCN: number,
    luong_thuc_nhan: number,
  }